<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class SpecialitySeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('specialities')->insert([
            ['name' => 'Cardiologist'],
            ['name' => 'Oncologist'],
            ['name' => 'Neurologist'],
            ['name' => 'Orthopedic Surgeon'],
            ['name' => 'Dermatologist'],
            ['name' => 'Pediatrician'],
            ['name' => 'Gastroenterologist'],
            ['name' => 'Endocrinologist'],
            ['name' => 'Pulmonologist'],
            ['name' => 'Ophthalmologist'],
            ['name' => 'Radiologist'],
            ['name' => 'Urologist'],
            ['name' => 'Nephrologist'],
            ['name' => 'Rheumatologist'],
            ['name' => 'Hematologist'],
            ['name' => 'Psychiatrist'],
            ['name' => 'Allergist/Immunologist'],
            ['name' => 'Infectious Disease Specialist'],
            ['name' => 'Plastic Surgeon'],
            ['name' => 'Otolaryngologist (ENT)'],
            ['name' => 'Anesthesiologist'],
            ['name' => 'Neurosurgeon'],
            ['name' => 'Neonatologist'],
            ['name' => 'Pediatric Cardiologist'],
            ['name' => 'Pediatric Oncologist'],
            ['name' => 'Pediatric Neurologist'],
            ['name' => 'Pediatric Orthopedic Surgeon'],
            ['name' => 'Pediatric Endocrinologist'],
            ['name' => 'Pediatric Pulmonologist'],
            ['name' => 'Pediatric Gastroenterologist'],
            ['name' => 'Pediatric Rheumatologist'],
            ['name' => 'Pediatric Hematologist'],
            ['name' => 'Developmental Pediatrician'],
            ['name' => 'Cardiac Electrophysiologist'],
            ['name' => 'Interventional Cardiologist'],
            ['name' => 'Interventional Radiologist'],
            ['name' => 'Pediatric Surgeon'],
            ['name' => 'Colorectal Surgeon'],
            ['name' => 'Hepatologist'],
            ['name' => 'Interventional Neurologist'],
            ['name' => 'Clinical Geneticist'],
            ['name' => 'Pain Management Specialist'],
            ['name' => 'Sports Medicine Physician'],
            ['name' => 'Physical Medicine and Rehabilitation Physician'],
            ['name' => 'Sleep Medicine Specialist'],
            ['name' => 'Addiction Psychiatrist'],
            ['name' => 'Forensic Psychiatrist'],
            ['name' => 'Reproductive Endocrinologist'],
            ['name' => 'Andrologist'],
            ['name' => 'Hand Surgeon'],
            ['name' => 'Bariatric Surgeon'],
            ['name' => 'Vascular Surgeon'],
            ['name' => 'Thoracic Surgeon'],
            ['name' => 'Pediatric Nephrologist'],
            ['name' => 'Pediatric Rheumatologist'],
            ['name' => 'Pediatric Infectious Disease Specialist'],
            ['name' => 'Pediatric Pulmonologist'],
            ['name' => 'Pediatric Gastroenterologist'],
            ['name' => 'Pediatric Cardiac Surgeon'],
            ['name' => 'Pediatric Orthopedic Surgeon'],
            ['name' => 'Pediatric Endocrinologist'],
            ['name' => 'Pediatric Hematologist'],
            ['name' => 'Pediatric Dermatologist'],
            ['name' => 'Pediatric Ophthalmologist'],
            ['name' => 'Pediatric Otolaryngologist (ENT)'],
            ['name' => 'Pediatric Radiologist'],
            ['name' => 'Pediatric Anesthesiologist'],
            ['name' => 'Pediatric Oncologist'],
            ['name' => 'Pediatric Allergist/Immunologist'],
            ['name' => 'Pediatric Neurosurgeon'],
            ['name' => 'Pediatric Developmental Behavioral Pediatrician'],
            ['name' => 'Pediatric Adolescent Medicine Specialist'],
            ['name' => 'Pediatric Emergency Medicine Physician'],
            ['name' => 'Neonatal-Perinatal Medicine Specialist'],
            ['name' => 'Pediatric Critical Care Specialist'],
            ['name' => 'Pediatric Hospitalist'],
            ['name' => 'Pediatric Infectious Disease Specialist'],
            ['name' => 'Pediatric Nephrologist'],
            ['name' => 'Pediatric Cardiologist'],
            ['name' => 'Pediatric Endocrinologist'],
            ['name' => 'Pediatric Rheumatologist'],
            ['name' => 'Pediatric Gastroenterologist'],
            ['name' => 'Pediatric Pulmonologist'],
            ['name' => 'Pediatric Hematologist'],
            ['name' => 'Pediatric Dermatologist'],
            ['name' => 'Pediatric Neurologist'],
            ['name' => 'Pediatric Ophthalmologist'],
            ['name' => 'Pediatric Otolaryngologist (ENT)'],
            ['name' => 'Pediatric Radiologist'],
            ['name' => 'Pediatric Anesthesiologist'],
            ['name' => 'Pediatric Oncologist'],
            ['name' => 'Pediatric Allergist/Immunologist'],
            ['name' => 'Pediatric Surgeon'],
            ['name' => 'Pediatric Colorectal Surgeon'],
            ['name' => 'Pediatric Hepatologist'],
            ['name' => 'Pediatric Interventional Neurologist'],
            ['name' => 'Pediatric Clinical Geneticist'],
        ]);
    }
}
