export const documentTypeOptions = [
    { value: '', label: 'Select Document Type' },
    { value: 'Disease History', label: 'Disease History' },
    { value: 'Survey Results', label: 'Survey Results' },
    { value: 'Diagnostic Reports', label: 'Diagnostic Reports' },
    { value: 'X-rays and Reports', label: 'X-rays and Reports' },
    { value: 'Ultrasound Examinations', label: 'Ultrasound Examinations' },
    { value: 'MRI and CT Scans', label: 'MRI and CT Scans' },
    { value: 'Recipes', label: 'Recipes' },
    { value: 'Electronic Prescriptions for Drugs', label: 'Electronic Prescriptions for Drugs' },
    { value: 'Instructions for Using Medications', label: 'Instructions for Using Medications' },
    { value: 'Referrals for Laboratory Tests', label: 'Referrals for Laboratory Tests' },
    { value: 'Referrals to Specialist Consultations', label: 'Referrals to Specialist Consultations' },
    { value: 'Referrals for Hospitalization', label: 'Referrals for Hospitalization' },
    { value: 'Health Monitoring Reports', label: 'Health Monitoring Reports' },
    { value: 'Medical Certificates', label: 'Medical Certificates' },
];
